import { jsPDF } from "jspdf";

function text(value: unknown, fallback = "Not provided"): string {
  const s = String(value ?? "").trim();
  return s || fallback;
}

function list(values: unknown, fallback = "Not provided"): string[] {
  if (!Array.isArray(values)) return fallback ? [fallback] : [];
  const out = values.map((v) => String(v ?? "").trim()).filter(Boolean);
  return out.length ? out : [fallback];
}

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFillColor(23, 37, 84);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 16, 16);
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(subtitle, 16, 22);
  }
  doc.setTextColor(30, 41, 59);
}

function section(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, y, 182, 8, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text(title.toUpperCase(), 18, y + 5.5);
  return y + 13;
}

function wrapped(doc: jsPDF, value: string, x: number, y: number, width: number, fontSize = 9, lineHeight = 4.5): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(fontSize);
  const lines = doc.splitTextToSize(value, width) as string[];
  for (const line of lines) {
    if (y > 278) { doc.addPage(); addHeader(doc, "Interview Cracker Report"); y = 38; }
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

function bulletList(doc: jsPDF, values: string[], x: number, y: number, width: number): number {
  for (const value of values) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.text("-", x, y);
    y = wrapped(doc, value, x + 4, y, width - 4, 8.5, 4.2) + 1.5;
    if (y > 278) { doc.addPage(); addHeader(doc, "Interview Cracker Report"); y = 38; }
  }
  return y;
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page++) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(`Interview Cracker • Page ${page} of ${pages}`, 16, 289);
  }
}

function save(doc: jsPDF, filename: string) {
  addFooter(doc);
  doc.save(filename);
}

export function downloadAtsReport(analysis: any) {
  const doc = new jsPDF();
  addHeader(doc, "ATS Resume Report", `${text(analysis?.personalInfo?.fullName, "Candidate")} • Generated by Interview Cracker`);
  let y = 38;
  doc.setFont("helvetica", "bold"); doc.setFontSize(28); doc.setTextColor(37, 99, 235);
  doc.text(`${Number(analysis?.atsScore || 0)}/100`, 16, y); y += 10;
  doc.setFontSize(10); doc.setTextColor(71, 85, 105); doc.setFont("helvetica", "normal");
  doc.text("ATS compatibility score based on the uploaded resume analysis.", 16, y); y += 10;

  y = section(doc, "Candidate", y);
  y = wrapped(doc, `${text(analysis?.personalInfo?.email)} | ${text(analysis?.personalInfo?.phone)} | ${text(analysis?.personalInfo?.location)}`, 16, y, 178) + 4;
  y = wrapped(doc, `Target role: ${list(analysis?.candidateProfile?.targetRoles).join(", ")}`, 16, y, 178) + 6;

  y = section(doc, "Resume Strengths", y);
  y = bulletList(doc, list(analysis?.resumeQualityReport?.strengths, "No strengths recorded."), 18, y, 174) + 4;
  y = section(doc, "Weaknesses", y);
  y = bulletList(doc, list(analysis?.resumeQualityReport?.weaknesses, "No weaknesses recorded."), 18, y, 174) + 4;
  y = section(doc, "Keyword Findings", y);
  y = wrapped(doc, `Relevant: ${list(analysis?.keywordAnalysis?.relevant).join(", ")}`, 16, y, 178) + 3;
  y = wrapped(doc, `Missing: ${list(analysis?.keywordAnalysis?.missing).join(", ")}`, 16, y, 178) + 3;
  y = wrapped(doc, `Overused: ${list(analysis?.keywordAnalysis?.overused, "None recorded.").join(", ")}`, 16, y, 178) + 3;
  y = section(doc, "Recommendations", y);
  y = bulletList(doc, list((analysis?.resumeQualityReport?.recommendations || []).map((r: any) => `${r.action || "Recommendation"} - ${r.impact || ""}`), "No recommendations recorded."), 18, y, 174);
  save(doc, "ATS_Report.pdf");
}

export function downloadResumeReport(analysis: any) {
  const doc = new jsPDF();
  addHeader(doc, "Resume Quality Report", `${text(analysis?.personalInfo?.fullName, "Candidate")} • Detailed analysis`);
  let y = 38;
  y = section(doc, "Overall Assessment", y);
  y = wrapped(doc, `ATS score: ${Number(analysis?.atsScore || 0)}/100`, 16, y, 178) + 3;
  y = wrapped(doc, `Grammar score: ${Number(analysis?.grammarAnalysis?.score || 0)}/100`, 16, y, 178) + 3;
  y = wrapped(doc, `Tone: ${text(analysis?.grammarAnalysis?.tone)} | Readability: ${text(analysis?.grammarAnalysis?.readability)}`, 16, y, 178) + 6;
  y = section(doc, "Strengths", y); y = bulletList(doc, list(analysis?.resumeQualityReport?.strengths), 18, y, 174) + 4;
  y = section(doc, "Critical Issues", y); y = bulletList(doc, list(analysis?.resumeQualityReport?.criticalIssues, "No critical issues recorded."), 18, y, 174) + 4;
  y = section(doc, "Medium Issues", y); y = bulletList(doc, list(analysis?.resumeQualityReport?.mediumIssues, "No medium issues recorded."), 18, y, 174) + 4;
  y = section(doc, "Minor Improvements", y); y = bulletList(doc, list(analysis?.resumeQualityReport?.minorIssues, "No minor issues recorded."), 18, y, 174) + 4;
  y = section(doc, "Recommendations", y); y = bulletList(doc, list((analysis?.resumeQualityReport?.recommendations || []).map((r: any) => `${r.action || "Recommendation"} - ${r.impact || ""}`), "No recommendations recorded."), 18, y, 174);
  save(doc, "Resume_Report.pdf");
}

export function downloadImprovedResume(analysis: any) {
  const doc = new jsPDF();
  const pi = analysis?.personalInfo || {};
  const cp = analysis?.candidateProfile || {};
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold"); doc.setFontSize(22);
  doc.text(text(pi.fullName, "Candidate"), 16, 18);
  doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(71,85,105);
  doc.text([text(pi.email), text(pi.phone), text(pi.location)].filter(Boolean).join(" | "), 16, 24);
  let y = 34;
  const resumeSection = (title: string) => { y = section(doc, title, y); };
  const addBody = (value: string) => { y = wrapped(doc, value, 16, y, 178, 9.5, 4.8) + 5; };

  resumeSection("Professional Summary");
  addBody(text(analysis?.resumeImprovement?.improvedProfessionalSummary));
  if (text(cp.targetRoles, "").trim()) { resumeSection("Target Role"); addBody(list(cp.targetRoles).join(", ")); }
  resumeSection("Skills");
  addBody(`Languages: ${list(analysis?.skillsAnalysis?.programmingLanguages).join(", ")}\nFrameworks: ${list(analysis?.skillsAnalysis?.frameworks).join(", ")}\nTools: ${list(analysis?.skillsAnalysis?.tools).join(", ")}\nDatabases: ${list(analysis?.skillsAnalysis?.databases).join(", ")}\nCloud: ${list(analysis?.skillsAnalysis?.cloud).join(", ")}`);
  if (Array.isArray(analysis?.workExperience) && analysis.workExperience.length) {
    resumeSection("Experience");
    for (const exp of analysis.workExperience) { addBody(`${text(exp.title)} - ${text(exp.company)}${exp.duration ? ` (${exp.duration})` : ""}\n${text(exp.description)}`); }
  }
  resumeSection("Projects");
  const projects = Array.isArray(analysis?.projectsAnalysis) ? analysis.projectsAnalysis : [];
  for (const project of projects.filter((x: any) => x && typeof x === "object")) {
    addBody(`${text(project.title)}\n${text(project.description)}\nTechnologies: ${list(project.techStack).join(", ")}`);
  }
  if (Array.isArray(analysis?.achievements) && analysis.achievements.length) { resumeSection("Achievements"); addBody(analysis.achievements.map((a:any)=>text(a)).join("\n")); }
  resumeSection("Education");
  addBody(`${text(pi.degree)} - ${text(pi.branch)}\n${text(pi.college)}${pi.graduationYear ? ` • ${pi.graduationYear}` : ""}${pi.cgpa ? ` • CGPA/GPA: ${pi.cgpa}` : ""}`);
  save(doc, "Improved_Resume.pdf");
}

export function downloadMasterProfile(analysis: any) {
  const doc = new jsPDF();
  addHeader(doc, "Master Candidate Profile", `${text(analysis?.personalInfo?.fullName, "Candidate")} • Interview Cracker`);
  let y = 38;
  y = section(doc, "Profile", y);
  y = wrapped(doc, `Category: ${text(analysis?.candidateProfile?.candidateCategory)} | Confidence: ${Number(analysis?.candidateProfile?.confidenceLevel || 0)}/100`, 16, y, 178) + 4;
  y = wrapped(doc, `Target roles: ${list(analysis?.candidateProfile?.targetRoles).join(", ")}`, 16, y, 178) + 3;
  y = wrapped(doc, `Target companies: ${list(analysis?.candidateProfile?.targetCompanies).join(", ")}`, 16, y, 178) + 6;
  y = section(doc, "Skills", y);
  y = wrapped(doc, `Languages: ${list(analysis?.skillsAnalysis?.programmingLanguages).join(", ")}\nFrameworks: ${list(analysis?.skillsAnalysis?.frameworks).join(", ")}\nTools: ${list(analysis?.skillsAnalysis?.tools).join(", ")}\nDatabases: ${list(analysis?.skillsAnalysis?.databases).join(", ")}\nCloud: ${list(analysis?.skillsAnalysis?.cloud).join(", ")}`, 16, y, 178, 9, 4.5) + 6;
  y = section(doc, "Strengths", y); y = bulletList(doc, list(analysis?.resumeQualityReport?.strengths), 18, y, 174) + 4;
  y = section(doc, "Weaknesses", y); y = bulletList(doc, list(analysis?.resumeQualityReport?.weaknesses), 18, y, 174) + 4;
  y = section(doc, "Recommended Practice Areas", y); y = bulletList(doc, list(analysis?.candidateProfile?.personalization?.recommendedPracticeAreas), 18, y, 174) + 4;
  y = section(doc, "Resume Evidence", y); y = wrapped(doc, `ATS: ${Number(analysis?.atsScore || 0)}/100\nGrammar: ${Number(analysis?.grammarAnalysis?.score || 0)}/100\nSections detected: ${list(analysis?.sectionsFound).join(", ")}`, 16, y, 178);
  save(doc, "Master_Profile.pdf");
}
